obstacles:
    -   type: Polygon
        vertices:
          - [1.2, 1.2]
          - [2.8, 1.2]
          - [2.8, 1.8]
          - [1.2, 1.8]

    -   type: Polygon
        vertices:
          - [1.2, 2.0]
          - [1.8, 2.0]
          - [1.8, 2.8]
          - [1.2, 2.8]

    -   type: Polygon
        vertices:
          - [5.2, 0.2]
          - [6.0, 0.2]
          - [6.0, 2.4]
          - [5.2, 2.4]

    -   type: Polygon
        vertices:
          - [6.2, 1.6]
          - [7.0, 1.6]
          - [7.0, 2.4]
          - [6.2, 2.4]

    -   type: Polygon
        vertices:
          - [7.2, 1.6]
          - [8.0, 1.6]
          - [8.0, 2.4]
          - [7.2, 2.4]

    -   type: Polygon
        vertices:
          - [8.2, 1.6]
          - [9.0, 1.6]
          - [9.0, 2.4]
          - [8.2, 2.4]

    -   type: Polygon
        vertices:
          - [7.2, 2.6]
          - [8.0, 2.6]
          - [8.0, 3.4]
          - [7.2, 3.4]

    -   type: Polygon
        vertices:
          - [3.2, 3.0]
          - [4.0, 3.0]
          - [4.0, 3.8]
          - [3.2, 3.8]

    -   type: Polygon
        vertices:
          - [3.2, 4.0]
          - [4.0, 4.0]
          - [4.0, 4.8]
          - [3.2, 4.8]

    -   type: Polygon
        vertices:
          - [4.2, 3.5]
          - [5.0, 3.5]
          - [5.0, 4.3]
          - [4.2, 4.3]

    -   type: Polygon
        vertices:
          - [5.2, 3.5]
          - [6.0, 3.5]
          - [6.0, 4.3]
          - [5.2, 4.3]

    -   type: Polygon
        vertices:
          - [0.2, 4.5]
          - [1.5, 4.5]
          - [1.5, 5.3]
          - [0.2, 5.3]

    -   type: Polygon
        vertices:
          - [1.6, 6.6]
          - [2.2, 6.6]
          - [2.2, 8.0]
          - [1.6, 8.0]

    -   type: Polygon
        vertices:
          - [2.4, 6.6]
          - [3.8, 6.6]
          - [3.8, 7.2]
          - [2.4, 7.2]

    -   type: Polygon
        vertices:
          - [3.4, 6.0]
          - [3.8, 6.0]
          - [3.8, 6.4]
          - [3.4, 6.4]

    -   type: Polygon
        vertices:
          - [9.8, 5.2]
          - [8.6, 5.2]
          - [8.6, 4.6]
          - [9.8, 4.6]

    -   type: Polygon
        vertices:
          - [8.4, 4.6]
          - [8.4, 6.4]
          - [7.6, 6.4]
          - [7.6, 4.6]

    -   type: Polygon
        vertices:
          - [6.4, 5.8]
          - [7.4, 5.8]
          - [7.4, 6.4]
          - [6.4, 6.4]

    -   type: Polygon
        vertices:
          - [5.6, 5.4]
          - [6.2, 5.4]
          - [6.2, 7.4]
          - [5.6, 7.4]

    -   type: Polygon
        vertices:
          - [1.6, 9.0]
          - [2.2, 9.0]
          - [2.2, 9.8]
          - [1.6, 9.8]

    -   type: Polygon
        vertices:
          - [3.8, 8.4]
          - [5.6, 8.4]
          - [5.6, 9.0]
          - [3.8, 9.0]

    -   type: Polygon
        vertices:
          - [5.8, 8.4]
          - [7.6, 8.4]
          - [7.6, 9.0]
          - [5.8, 9.0]

    -   type: Polygon
        vertices:
          - [7.8, 8.4]
          - [8.4, 8.4]
          - [8.4, 9.0]
          - [7.8, 9.0]

workspace:
    -  type: Polygon
       vertices:
          - [0.0, 0.0]
          - [10.0, 0.0]
          - [10.0, 10.0]
          - [0.0, 10.0]