obstacles:
    -   type: Polygon
        vertices:
          - [1.2, 1.2]
          - [2.8, 1.2]
          - [2.8, 1.8]
          - [1.8, 1.8]
          - [1.8, 2.8]
          - [1.2, 2.8]

    -   type: Polygon
        vertices:
          - [5.2, -0.1]
          - [6.0, -0.1]
          - [6.0, 1.6]
          - [9.0, 1.6]
          - [9.0, 2.4]
          - [8.0, 2.4]
          - [8.0, 3.4]
          - [7.2, 3.4]
          - [7.2, 2.4]
          - [5.2, 2.4]

    -   type: Polygon
        vertices:
          - [3.2, 3.0]
          - [4.0, 3.0]
          - [4.0, 3.5]
          - [6.0, 3.5]
          - [6.0, 4.3]
          - [4.0, 4.3]
          - [4.0, 4.8]
          - [3.2, 4.8]

    -   type: Polygon
        vertices:
          - [-0.1, 4.5]
          - [1.5, 4.5]
          - [1.5, 5.3]
          - [-0.1, 5.3]

    -   type: Polygon
        vertices:
          - [1.6, 6.6]
          - [3.4, 6.6]
          - [3.4, 6.0]
          - [3.8, 6.0]
          - [3.8, 7.2]
          - [2.2, 7.2]
          - [2.2, 8.0]
          - [1.6, 8.0]

    -   type: Polygon
        vertices:
          - [10.1, 5.2]
          - [8.4, 5.2]
          - [8.4, 6.4]
          - [6.2, 6.4]
          - [6.2, 7.4]
          - [5.6, 7.4]
          - [5.6, 5.4]
          - [6.2, 5.4]
          - [6.2, 5.8]
          - [7.6, 5.8]
          - [7.6, 4.6]
          - [10.1, 4.6]

    -   type: Polygon
        vertices:
          - [1.6, 9.0]
          - [2.2, 9.0]
          - [2.2, 10.1]
          - [1.6, 10.1]

    -   type: Polygon
        vertices:
          - [3.8, 8.4]
          - [8.4, 8.4]
          - [8.4, 9.0]
          - [3.8, 9.0]

workspace:
    -  type: Polygon
       vertices:
          - [0.0, 0.0]
          - [10.0, 0.0]
          - [10.0, 10.0]
          - [0.0, 10.0]