obstacles:
    -  type: Polygon
       vertices:
          - [0.0, 0.0]
          - [6.3, 0.0]
          - [6.3, 2.0]
          - [6.8, 2.0]
          - [6.8, 0.0]
          - [10.0, 0.0]
          - [10.0, 5.5]
          - [5.5, 5.5]
          - [5.5, 6.0]
          - [10.0, 6.0]
          - [10.0, 10.0]
          - [4.0, 10.0]
          - [4.0, 8.0]
          - [8.5, 8.0]
          - [8.5, 7.5]
          - [4.0, 7.5]
          - [4.0, 4.0]
          - [8.5, 4.0]
          - [8.5, 2.0]
          - [8.0, 2.0]
          - [8.0, 3.5]
          - [5.0, 3.5]
          - [5.0, 1.0]
          - [1.5, 1.0]
          - [1.5, 2.0]
          - [3.0, 2.0]
          - [3.0, 3.5]
          - [0.0, 3.5]
workspace:
    -  type: Polygon
       vertices:
          - [-5.0, -5.0]
          - [15.0, -5.0]
          - [15.0, 15.0]
          - [-5.0, 15.0]