obstacles:
# 原obstacle
    -   type: Polygon
        vertices:
          - [1.0,-0.16]
          - [1.4,-0.16]
          - [1.4,0.54]
          - [1.0,0.54]

    -   type: Polygon
        vertices:
          - [3.2,-0.195]
          - [3.6,-0.195]
          - [3.6,1.0]
          - [4.0,1.0]
          - [4.0,1.4]
          - [3.2,1.4]

    -   type: Polygon
        vertices:
          - [5.1,-0.195]
          - [5.5,-0.195]
          - [5.5,1.0]
          - [5.9,1.0]
          - [5.9,1.4]
          - [4.7,1.4]
          - [4.7,1.0]
          - [5.1,1.0]

    -   type: Polygon
        vertices:
          - [6.48,1.0]
          - [7.18,1.0]
          - [7.18,1.4]
          - [6.48,1.4]

    -   type: Polygon
        vertices:
          - [-0.2,1.1]
          - [1.4,1.1]
          - [1.4,2.0]
          - [1.0,2.0]
          - [1.0,1.5]
          - [-0.2,1.5]

    -   type: Polygon
        vertices:
          - [1.9,0.8]
          - [2.5,0.8]
          - [2.5,2.0]
          - [1.9,2.0]

    -   type: Polygon
        vertices:
          - [3.7,2.0]
          - [4.7,2.0]
          - [4.7,3.2]
          - [4.3,3.2]
          - [4.3,2.4]
          - [3.7,2.4]

    -   type: Polygon
        vertices:
          - [5.38,2.0]
          - [7.18,2.0]
          - [7.18,2.4]
          - [5.78,2.4]
          - [5.78,2.8]
          - [5.38,2.8]

    -   type: Polygon
        vertices:
          - [-0.2,2.6]
          - [0.6,2.6]
          - [0.6,3.0]
          - [-0.2,3.0]

    -   type: Polygon
        vertices:
          - [1.3,2.6]
          - [3.3,2.6]
          - [3.3,3.4]
          - [2.9,3.4]
          - [2.9,3.0]
          - [2.1,3.0]
          - [2.1,4.2]
          - [1.7,4.2]
          - [1.7,3.0]
          - [1.3,3.0]

    -   type: Polygon
        vertices:
          - [5.4,3.5]
          - [5.8,3.5]
          - [5.8,4.2]
          - [5.4,4.2]


# [[[1.9, 0.8], [2.5, 0.8], [2.5, 2.0], [1.9, 2.0]],
# [[3.5, 2.0], [4.5, 2.0], [4.5, 2.4], [3.5, 2.4]],
# [[4.3, 2.0], [4.7, 2.0], [4.7, 3.2], [4.3, 3.2]],
# [[5.38, 2.0], [7.18, 2.0], [7.18, 2.4], [5.38, 2.4]],
# [[5.38, 2.0], [5.78, 2.0], [5.78, 2.8], [5.38, 2.8]],
# [[5.38, 3.49], [5.78, 3.49], [5.78, 4.19], [5.38, 4.19]],
# [[5.1, -0.195], [5.5, -0.195], [5.5, 1.205], [5.1, 1.205]],
# [[4.7, 1.0], [5.7, 1.0], [5.7, 1.4], [4.7, 1.4]],
# [[3.2, -0.195], [3.6, -0.195], [3.6, 1.205], [3.2, 1.205]],
# [[3.2, 1.0], [4.0, 1.0], [4.0, 1.4], [3.2, 1.4]],
# [[6.48, 1.0], [7.18, 1.0], [7.18, 1.4], [6.48, 1.4]],
# [[1.7, 2.8], [2.1, 2.8], [2.1, 4.2], [1.7, 4.2]],
# [[1.3, 2.8], [3.1, 2.8], [3.1, 3.2], [1.3, 3.2]],
# [[2.9, 2.8], [3.3, 2.8], [3.3, 3.4], [2.9, 3.4]],
# [[-0.2, 2.8], [0.6, 2.8], [0.6, 3.2], [-0.2, 3.2]],
# [[-0.2, 1.1], [1.2, 1.1], [1.2, 1.5], [-0.2, 1.5]],
# [[1.0, 1.1], [1.4, 1.1], [1.4, 2.0], [1.0, 2.0]],
# [[1.0, -0.16], [1.4, -0.16], [1.4, 0.54], [1.0, 0.54]]]



workspace:
    -  type: Polygon
       vertices:
          - [0.0, 0.0]
          - [7.0, 0.0]
          - [7.0, 4.0]
          - [0.0, 4.0]