obstacles:
    -   type: Polygon
        vertices:
          - [1.1, -0.1]
          - [1.3, -0.1]
          - [1.3, 0.5]
          - [1.1, 0.5]

    -   type: Polygon
        vertices:
          - [3.3, -0.1]
          - [3.5, -0.1]
          - [3.5, 1.1]
          - [4.0, 1.1]
          - [4.0, 1.3]
          - [3.3, 1.3]

    -   type: Polygon
        vertices:
          - [5.2, -0.1]
          - [5.4, -0.1]
          - [5.4, 1.1]
          - [5.8, 1.1]
          - [5.8, 1.3]
          - [4.7, 1.3]
          - [4.7, 1.1]
          - [5.2, 1.1]

    -   type: Polygon
        vertices:
          - [6.6, 1.1]
          - [7.1, 1.1]
          - [7.1, 1.3]
          - [6.6, 1.3]

    -   type: Polygon
        vertices:
          - [-0.1, 1.2]
          - [1.3, 1.2]
          - [1.3, 2.0]
          - [1.1, 2.0]
          - [1.1, 1.4]
          - [-0.1, 1.4]

    -   type: Polygon
        vertices:
          - [2.05, 0.85]
          - [2.55, 0.85]
          - [2.55, 1.95]
          - [2.05, 1.95]

    -   type: Polygon
        vertices:
          - [3.6, 2.0]
          - [4.6, 2.0]
          - [4.6, 3.1]
          - [4.4, 3.1]
          - [4.4, 2.2]
          - [3.6, 2.2]

    -   type: Polygon
        vertices:
          - [5.4, 2.1]
          - [7.1, 2.1]
          - [7.1, 2.3]
          - [5.6, 2.3]
          - [5.6, 2.8]
          - [5.4, 2.8]

    -   type: Polygon
        vertices:
          - [-0.1, 2.9]
          - [0.5, 2.9]
          - [0.5, 3.1]
          - [-0.1, 3.1]

    -   type: Polygon
        vertices:
          - [1.4, 2.9]
          - [3.4, 2.9]
          - [3.4, 3.1]
          - [2.0, 3.1]
          - [2.0, 4.1]
          - [1.8, 4.1]
          - [1.8, 3.1]
          - [1.4, 3.1]

    -   type: Polygon
        vertices:
          - [5.4,3.6]
          - [5.6,3.6]
          - [5.6,4.1]
          - [5.4,4.1]


# [[[1.9, 0.8], [2.5, 0.8], [2.5, 2.0], [1.9, 2.0]],
# [[3.5, 2.0], [4.5, 2.0], [4.5, 2.4], [3.5, 2.4]],
# [[4.3, 2.0], [4.7, 2.0], [4.7, 3.2], [4.3, 3.2]],
# [[5.38, 2.0], [7.18, 2.0], [7.18, 2.4], [5.38, 2.4]],
# [[5.38, 2.0], [5.78, 2.0], [5.78, 2.8], [5.38, 2.8]],
# [[5.38, 3.49], [5.78, 3.49], [5.78, 4.19], [5.38, 4.19]],
# [[5.1, -0.195], [5.5, -0.195], [5.5, 1.205], [5.1, 1.205]],
# [[4.7, 1.0], [5.7, 1.0], [5.7, 1.4], [4.7, 1.4]],
# [[3.2, -0.195], [3.6, -0.195], [3.6, 1.205], [3.2, 1.205]],
# [[3.2, 1.0], [4.0, 1.0], [4.0, 1.4], [3.2, 1.4]],
# [[6.48, 1.0], [7.18, 1.0], [7.18, 1.4], [6.48, 1.4]],
# [[1.7, 2.8], [2.1, 2.8], [2.1, 4.2], [1.7, 4.2]],
# [[1.3, 2.8], [3.1, 2.8], [3.1, 3.2], [1.3, 3.2]],
# [[2.9, 2.8], [3.3, 2.8], [3.3, 3.4], [2.9, 3.4]],
# [[-0.2, 2.8], [0.6, 2.8], [0.6, 3.2], [-0.2, 3.2]],
# [[-0.2, 1.1], [1.2, 1.1], [1.2, 1.5], [-0.2, 1.5]],
# [[1.0, 1.1], [1.4, 1.1], [1.4, 2.0], [1.0, 2.0]],
# [[1.0, -0.16], [1.4, -0.16], [1.4, 0.54], [1.0, 0.54]]]

workspace:
    -  type: Polygon
       vertices:
          - [0.0, 0.0]
          - [7.0, 0.0]
          - [7.0, 4.0]
          - [0.0, 4.0]