obstacles:
        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 2.0
                               - 2.8
                         width: 0.8
                         height: 0.8
                         theta: 0.0
                         s: 0.99


        -    shape: StarTree
             stars:
                     -   type: Rectangular
                         center:
                               - 3.25
                               - 3.1
                         width: 0.2
                         height: 0.9
                         theta: -0.2
                         s: 0.6

                     -   type: Rectangular
                         center:
                               - 3.55
                               - 2.55
                         width: 0.9
                         height: 0.2
                         theta: -0.4
                         s: 0.6

        -    shape: StarTree
             stars:
                     -   type: Rectangular
                         center:
                               - 2.2
                               - 1.0
                         width: 0.2
                         height: 0.8
                         theta: -0.5
                         s: 0.99

                     -   type: Rectangular
                         center:
                               - 2.07
                               - 1.42
                         width: 0.8
                         height: 0.2
                         theta: -0.5
                         s: 0.99


        -    shape: StarTree
             stars:
                     -   type: Rectangular
                         center:
                               - 3.2
                               - 1.25
                         width: 0.2
                         height: 0.7
                         theta: 0.0
                         s: 0.99

                     -   type: Rectangular
                         center:
                               - 3.65
                               - 1.0
                         width: 1.1
                         height: 0.2
                         theta: 0.0
                         s: 0.99
                    
                     -   type: Rectangular
                         center:
                               - 4.1
                               - 1.25
                         width: 0.2
                         height: 0.7
                         theta: 0.0
                         s: 0.99


workspace:
        -   shape: StarTree
            stars:
                    -   type: Workspace
                        center:
                              - 3.5
                              - 2.0
                        width: 7.0
                        height: 4.0
                        theta: 0.0
                        s: 0.999