obstacles:
        -    shape: Star
             star:
                    -    type: Rectangular
                         center:
                               - 6.77
                               - 1.1
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.99


        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 1.81
                               - 1.16
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.0

        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 1.81
                               - 1.64
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.0


        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 2.95
                               - 1.16
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.0

        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 2.95
                               - 1.64
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.0


        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 2.38
                               - 1.35
                         width: 0.5
                         height: 1.2
                         theta: 0.0
                         s: 0.99


        -    shape: StarTree
             stars:
                     -   type: Rectangular
                         center:
                               - 4.27
                               - 2.22
                         width: 0.8
                         height: 0.2
                         theta: 0.5
                         s: 0.99

                     -   type: Rectangular
                         center:
                               - 4.3
                               - 2.8
                         width: 0.2
                         height: 1.2
                         theta: 0.5
                         s: 0.99


workspace:
        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.9999

                    -    type: Rectangular
                         center:
                               - 6.38
                               - 2.2
                         width: 1.6
                         height: 0.2
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 5.6
                               - 2.48
                         width: 0.2
                         height: 0.7
                         theta: 0.2
                         s: 0.99

        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 5.6
                               - 3.84
                         width: 0.2
                         height: 0.7
                         theta: -0.2
                         s: 0.99


        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 5.4
                               - 0.505
                         width: 0.2
                         height: 1.4
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 5.6
                               - 1.1
                         width: 0.6
                         height: 0.2
                         theta: 0.0
                         s: 0.99

        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 3.85
                               - 0.505
                         width: 0.2
                         height: 1.4
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 4.15
                               - 1.1
                         width: 0.8
                         height: 0.2
                         theta: 0.0
                         s: 0.99

        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99


        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 1.8
                               - 3.5
                         width: 0.2
                         height: 1.4
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 2.2
                               - 2.9
                         width: 1.8
                         height: 0.2
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 3.0
                               - 3.1
                         width: 0.2
                         height: 0.6
                         theta: 0.0
                         s: 0.99

        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 0.2
                               - 2.9
                         width: 0.8
                         height: 0.2
                         theta: 0.0
                         s: 0.99

        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 0.4
                               - 1.2
                         width: 1.2
                         height: 0.2
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 0.9
                               - 1.5
                         width: 0.2
                         height: 0.8
                         theta: 0.0
                         s: 0.99

        -   shape: StarTree
            stars:
                    -    type: Workspace
                         center:
                               - 3.5
                               - 2.0
                         width: 7.0
                         height: 4.0
                         theta: 0.0
                         s: 0.99

                    -    type: Rectangular
                         center:
                               - 1.1
                               - 0.12
                         width: 0.2
                         height: 0.6
                         theta: 0.0
                         s: 0.99

#nf_lambda=1e2, nf_mu = [1e25, 1e16, 1e10]