obstacles:
    -   type: Polygon
        vertices:
          - [3.0, -0.1]
          - [3.4, -0.1]
          - [3.4, 1.2]
          - [8.5, 1.2]
          - [8.5, 1.6]
          - [7.0, 1.6]
          - [7.0, 3.4]
          - [6.6, 3.4]
          - [6.6, 1.6]
          - [3.0, 1.6]

    -   type: Polygon
        vertices:
          - [-0.1, 1.2]
          - [1.6, 1.2]
          - [1.6, 1.6]
          - [-0.1, 1.6]

    -   type: Polygon
        vertices:
          - [-0.1, 6.5]
          - [1.6, 6.5]
          - [1.6, 6.9]
          - [-0.1, 6.9]

    -   type: Polygon
        vertices:
          - [10.1, 3.0]
          - [8.4, 3.0]
          - [8.4, 3.4]
          - [10.1, 3.4]

    -   type: Polygon
        vertices:
          - [10.1, 8.2]
          - [6.6, 8.2]
          - [6.6, 5.2]
          - [3.4, 5.2]
          - [3.4, 8.2]
          - [4.7, 8.2]
          - [4.7, 6.5]
          - [5.1, 6.5]
          - [5.1, 8.6]
          - [1.2, 8.6]
          - [1.2, 8.2]
          - [3.0, 8.2]
          - [3.0, 5.2]
          - [1.2, 5.2]
          - [1.2, 3.0]
          - [1.6, 3.0]
          - [1.6, 4.8]
          - [4.7, 4.8]
          - [4.7, 3.4]
          - [3.0, 3.4]
          - [3.0, 3.0]
          - [5.1, 3.0]
          - [5.1, 4.8]
          - [8.7, 4.8]

          - [8.7, 7.0]
          - [8.3, 7.0]
          - [8.3, 5.2]
          - [7.0, 5.2]
          - [7.0, 7.8]
          - [10.1, 7.8]

workspace:
    -  type: Polygon
       vertices:
          - [0.0, 0.0]
          - [10.0, 0.0]
          - [10.0, 10.0]
          - [0.0, 10.0]