obstacles:
#    -   type: Polygon
#        vertices:
#            - [2.0, 1.0]
#            - [4.0, 1.0]
#            - [4.0, 2.0]
#            - [2.0, 2.0]
    -   type: Polygon
        vertices:
            - [2.0, 1.0]
            - [4.0, 1.0]
            - [4.0, 3.0]
            - [3.0, 3.0]
            - [3.0, 2.0]
            - [2.0, 2.0]


    -   type: Polygon
        vertices:
            - [5.0, 2.0]
            - [6.0, 2.0]
            - [6.0, 3.0]
            - [5.0, 3.0]

workspace:
    -   type: Polygon
        vertices:
            - [0.0, 0.0]
            - [7.0, 0.0]
            - [7.0, 4.0]
            - [0.0, 4.0]