obstacles:
        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 1.81
                               - 1.06
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.0

        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 1.81
                               - 1.74
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.0


        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 2.95
                               - 1.06
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.0

        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 2.95
                               - 1.74
                         width: 0.2
                         height: 0.2
                         theta: 0.0
                         s: 0.0


        -    shape: Star
             star:
                     -   type: Rectangular
                         center:
                               - 2.38
                               - 1.35
                         width: 0.5
                         height: 1.2
                         theta: 0.0
                         s: 0.99


        -    shape: StarTree
             stars:
                     -   type: Rectangular
                         center:
                               - 4.27
                               - 2.22
                         width: 0.8
                         height: 0.2
                         theta: 0.5
                         s: 0.99

                     -   type: Rectangular
                         center:
                               - 4.3
                               - 2.8
                         width: 0.2
                         height: 1.2
                         theta: 0.5
                         s: 0.99


workspace:
        -   shape: StarTree
            stars:
                    -   type: Workspace
                        center:
                              - 3.5
                              - 2.0
                        width: 7.0
                        height: 4.0
                        theta: 0.0
                        s: 0.999